# Generated by Django 4.0.3 on 2022-03-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('facility_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('number_of_medical_doctor', models.IntegerField(blank=True, null=True)),
                ('number_of_nurse', models.IntegerField(blank=True, null=True)),
                ('number_of_midwife', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('facility_types', models.ManyToManyField(to='facility.facilitytype')),
            ],
        ),
    ]
